name: Day - 3 Conditional Execution Workflow

on:
    workflow_dispatch:


jobs:
    conditional-demo:
        runs-on: ubuntu-latest
        env:
            TARGET_ENV: "dev"
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4
            
            - name: Always run step
              run: 
                  echo "This always runs ‚úÖ"
            - name: Run only on main branch
              if: github.ref_name == 'main'
              run: echo "You're on main branch üåø"
            - name: Run only if dev env
              if: env.TARGET_ENV == 'dev'
              run: echo "Deploying to development environment üöÄ"
            - name: Run on failure
              if: failure()
              run: echo "Something went wrong ‚ùå"
