name: Day 2 - Environment Variables & Contexts

on: 
    workflow_dispatch:

jobs:
    explore-env:
        runs-on: ubuntu-latest

        env:
            COURSE_NAME: "GitHub Actions 60-Day Challenge"
            DAY_NUMBER: 2
            AUTHOR: "Nirajan Singh"
            TARGET_ENV: "Staging"
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Print environment variables
              run: |
                echo "ğŸ“˜ Course: $COURSE_NAME"
                echo "ğŸ“… Day: $DAY_NUMBER"
                echo "ğŸ‘¨â€ğŸ’» Author: $AUTHOR"

            - name: Print GitHub context details
              run: |
                  echo "ğŸ§‘â€ğŸ“ Actor: ${{ github.actor }}"
                  echo "ğŸ  Repository: ${{github.repository}}"
                  echo "ğŸŒ¿ Branch: ${{github.ref_name}} "
                  echo "ğŸ•’ Run Number: ${{github.run_number}}"
                  echo "ğŸ”— Workflow URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
            - name: Step-level env example
              env:
                MOOD: "ğŸ”¥ Focused and ready!"
              run: |
                   echo "Current mood: $MOOD"

            - name: Combine contexts and env
              run: |
                 echo "Day $DAY_NUMBER by $AUTHOR run by ${{ github.actor}} from branch ${{github.ref_name}}"

                 echo "Deploying Day $DAY_NUMBER workflow by ${{github.actor}} to $TARGET_ENV environment ğŸš€ "



